# Generated by Django 3.2.2 on 2022-05-28 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Elenco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=100)),
                ('año_nacimiento', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, default='elenco-default.png', null=True, upload_to='')),
                ('resumen_biografico', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('elenco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.elenco')),
            ],
            bases=('administracion.elenco',),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('elenco_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='administracion.elenco')),
            ],
            bases=('administracion.elenco',),
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('resumen', models.TextField(max_length=300)),
                ('año_realización', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, default='pelicula-default.png', null=True, upload_to='')),
                ('estrella', models.FloatField()),
                ('categorias', models.ManyToManyField(related_name='peliculas', to='administracion.Categoria')),
                ('actores', models.ManyToManyField(related_name='peliculas', to='administracion.Actor')),
                ('directores', models.ManyToManyField(related_name='peliculas', to='administracion.Director')),
            ],
        ),
        migrations.CreateModel(
            name='Crítica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('comentario', models.TextField(max_length=300)),
                ('puntaje', models.PositiveSmallIntegerField()),
                ('valida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='administracion.pelicula')),
            ],
        ),
    ]
