# Generated by Django 3.2.2 on 2022-05-31 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='elenco',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='foto',
            field=models.ImageField(blank=True, default='pelicula-default.png', null=True, upload_to='peliculas/'),
        ),
    ]
