# Generated by Django 3.2.2 on 2022-05-31 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0002_auto_20220531_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elenco',
            name='foto',
        ),
        migrations.AddField(
            model_name='actor',
            name='foto',
            field=models.ImageField(blank=True, default='elenco-default.png', null=True, upload_to='actores/'),
        ),
        migrations.AddField(
            model_name='director',
            name='foto',
            field=models.ImageField(blank=True, default='elenco-default.png', null=True, upload_to='directores/'),
        ),
    ]
