# Generated by Django 3.2.2 on 2022-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_auto_20220531_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crítica',
            name='valida',
            field=models.BooleanField(default=None),
        ),
    ]
