# Generated by Django 3.2.2 on 2022-06-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_alter_crítica_valida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crítica',
            name='puntaje',
            field=models.FloatField(),
        ),
    ]
