# Generated by Django 3.2.2 on 2022-06-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_alter_crítica_puntaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crítica',
            name='valida',
            field=models.CharField(choices=[('espera', 'Esperando Validación'), ('rechazada', 'Rechazada'), ('valida', 'válida')], default='espera', max_length=100),
        ),
    ]
